##
# Here will be a bunch of aliases for interactive build shell
# This shell can be only spawned by ./envsetup --shell
##

# Pull user bashrc
source ~/.bashrc

# Also source core aliases
source ${P_ROOT}/build/developer/base/core.conf

clear

# Overwrite PS1 so dev knows we are in interactive shell
export PS1='\[\e[1;32m\]devenv [ \[\e[0m\]\w\[\e[1;32m\] ]$ \[\e[0m\]'

# Load all the toolset modules
# As this forces the loading modules again then send the output to nothingness
echo "Loading environment..."
source ${P_ROOT}/build/toolset/load_modules.sh > /dev/null
echo "Environment loaded"

# Clear trap and disable exit on error
trap - SIGINT INT
trap - ERR
set +e

# Sleep a bit
sleep 0.5

# Set user specific history file
export HISTFILE="${P_ROOT}/build/developer/users/$(whoami)/.bash_history"

# Pull existing user aliases.conf
# If not found then make empty one from Public user

who_am_i="${P_ROOT}/build/developer/users/$(whoami)"
public="${P_ROOT}/build/developer/users/Public"

if [ ! -f ${who_am_i}/aliases.conf ]; then
    mkdir -p ${who_am_i}
    cp -rf ${public}/* ${who_am_i}
    echo " " > ${who_am_i}/.bash_history
    message "User: $(whoami) configuration files copied over"
fi

# As the dev probably has some aliases overwritten in he's/her aliases then lets allow them to do it by sourcing aliases.conf here :)
source ${who_am_i}/aliases.conf

# Now lets clear the shell again
clear

message "run: help to see existing documented commands"
